// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1z9jvxVsuHFXnzmvcEg349tPYs7eBDx4',
    appId: '1:463049131674:web:be4d4a704658536f858123',
    messagingSenderId: '463049131674',
    projectId: 'testing-cli-ab36b',
    authDomain: 'testing-cli-ab36b.firebaseapp.com',
    storageBucket: 'testing-cli-ab36b.firebasestorage.app',
    measurementId: 'G-7R5QSDNR4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpzY3ZmPBAncHt_hiInFGS1Mr23tjiJIY',
    appId: '1:463049131674:android:01ac480e8dd96bc8858123',
    messagingSenderId: '463049131674',
    projectId: 'testing-cli-ab36b',
    storageBucket: 'testing-cli-ab36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FblyVzFIRTlc3EoNZkrn0KenG9VUrL4',
    appId: '1:463049131674:ios:2cb86cd3db7bc82b858123',
    messagingSenderId: '463049131674',
    projectId: 'testing-cli-ab36b',
    storageBucket: 'testing-cli-ab36b.firebasestorage.app',
    iosBundleId: 'com.example.mvcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6FblyVzFIRTlc3EoNZkrn0KenG9VUrL4',
    appId: '1:463049131674:ios:2cb86cd3db7bc82b858123',
    messagingSenderId: '463049131674',
    projectId: 'testing-cli-ab36b',
    storageBucket: 'testing-cli-ab36b.firebasestorage.app',
    iosBundleId: 'com.example.mvcProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1z9jvxVsuHFXnzmvcEg349tPYs7eBDx4',
    appId: '1:463049131674:web:bc9ff60e1fb268f6858123',
    messagingSenderId: '463049131674',
    projectId: 'testing-cli-ab36b',
    authDomain: 'testing-cli-ab36b.firebaseapp.com',
    storageBucket: 'testing-cli-ab36b.firebasestorage.app',
    measurementId: 'G-B2NYJTB6N2',
  );
}
